CREATE DATABASE BD_Floricultura

USE [BD_Floricultura]

/*-------------------------------------------------//-------------------------------------------------------*/


-- INICO DA CRIAÇÃO DE TABELAS --


CREATE TABLE TB_PESSOA(		
	ID_PESSOA INT IDENTITY(1,1) CONSTRAINT PK_TB_PESSOA
	PRIMARY KEY(ID_PESSOA),
	NUMERO_RG CHAR(9) CONSTRAINT CK_TB_PESSOA_NUM_RG CHECK(LEN(NUMERO_RG)= 9) NOT NULL,
	CPF CHAR(11) CONSTRAINT CK_TB_PESSOA_NUM_CPF CHECK(LEN(CPF)= 11) NOT NULL,
	NOME VARCHAR(100) NOT NULL,
	DTNASCIMENTO DATE NOT NULL,
	SEXO CHAR(1) NOT NULL,
	FONE VARCHAR(15) NOT NULL,
	ENDERECO VARCHAR(100) NOT NULL,
	DTCADASTRO DATE CONSTRAINT DF_DT_TB_PESSOA DEFAULT GETDATE() NOT NULL
);

CREATE TABLE TB_CLIENTE(	
	ID_CLIENTE INT IDENTITY(1,1) CONSTRAINT PK_TB_CLIENTE
	PRIMARY KEY(ID_CLIENTE),
	TIPO_CLIENTE CHAR(1) CONSTRAINT CK_TB_CLIENTE_TIPO CHECK(TIPO_CLIENTE IN('F','J')),
	FK_ID_PESSOA INT NOT NULL CONSTRAINT FK_PESSOA_ID_PESSOA_CLIENTE
	FOREIGN KEY(FK_ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)
);

CREATE TABLE TB_FUNCAO(
	ID_FUNC INT IDENTITY(1,1) CONSTRAINT PK_TB_FUNCAO
	PRIMARY KEY(ID_FUNC),
	DESCRICAO VARCHAR(50) NOT NULL
);

CREATE TABLE TB_FUNCIONARIO(	
	MATRICULA INT IDENTITY(1,1) CONSTRAINT PK_TB_FUNC
	PRIMARY KEY(MATRICULA),
	STATUS_FUNC VARCHAR(10) CONSTRAINT CK_TB_FUNCIONARIO_STATUS_FUNC
	CHECK(STATUS_FUNC IN('A','I','F')) NOT NULL,
	SALARIO SMALLMONEY NOT NULL,
	DTADMISSAO DATE NOT NULL CONSTRAINT DF_TB_FUNC_DTADMISSAO DEFAULT(GETDATE()),
	DTDMISSAO DATE NULL CONSTRAINT DF_TB_FUNC_DTDEMISSAO DEFAULT(GETDATE()),
	FK_ID_PESSOA INT NOT NULL CONSTRAINT FK_PESSOA_ID_PESSOA_FUNC
	FOREIGN KEY(FK_ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
	FK_FUNCAO INT NOT NULL CONSTRAINT FK_FUNCAO_ID_FUNCAO
	FOREIGN KEY (FK_FUNCAO) REFERENCES TB_FUNCAO(ID_FUNC)
);

CREATE TABLE TB_CATEGORIA(
	ID_CATEGORIA INT IDENTITY(1,1)
	CONSTRAINT PK_TB_CATEGRIA PRIMARY KEY(ID_CATEGORIA),
	DESCRICAO VARCHAR(50) NOT NULL 
);

CREATE TABLE TB_FORMA_PGTO(		
	ID_PGTO INT IDENTITY(1,1),
	DESCRICAO VARCHAR(20) NOT NULL,
	SIGLA VARCHAR(5) NOT NULL,
	CONSTRAINT PK_TB_FORMA_PGTO PRIMARY KEY(ID_PGTO)
);

CREATE TABLE TB_PRODUTO(
	NOME_PRODUTO VARCHAR(50) NOT NULL,
	COD_PRODUTO INT IDENTITY(1,1) CONSTRAINT PK_TB_PRODUTO
	PRIMARY KEY(COD_PRODUTO),
	VALOR SMALLMONEY NOT NULL, 
	QTDE_ESTOQUE SMALLINT NOT NULL,
	FK_ID_CATEGORIA INT NOT NULL CONSTRAINT FK_CATEGORIA_COD_CATEGORIA
	FOREIGN KEY(FK_ID_CATEGORIA) REFERENCES TB_CATEGORIA(ID_CATEGORIA)
);

CREATE TABLE TB_PEDIDO(	
	COD_PEDIDO INT IDENTITY(10000,1)
	CONSTRAINT PK_TB_PEDIDO PRIMARY KEY(COD_PEDIDO),
	NOTA_FISCAL SMALLINT,
	DTPEDIDO DATE NOT NULL CONSTRAINT DF_TB_PEDIDO_DATA DEFAULT(GETDATE()),
	FK_MATRICULA INT NOT NULL CONSTRAINT FK_FUNC_MATRICULA
	FOREIGN KEY(FK_MATRICULA)REFERENCES TB_FUNCIONARIO(MATRICULA),
	FK_ID_CLIENTE INT NOT NULL CONSTRAINT FK_CLIENTE_ID_CLIENTE
	FOREIGN KEY(FK_ID_CLIENTE)REFERENCES TB_CLIENTE(ID_CLIENTE)
);

CREATE TABLE TB_PEDIDO_PRODUTO(	
	ID_PEDIDO_PROD INT IDENTITY(1,1) CONSTRAINT PK_TB_PEDIDO_PROD
	PRIMARY KEY(ID_PEDIDO_PROD),
	FK_COD_PEDIDO INT NOT NULL CONSTRAINT FK_PEDIDO_COD_PEDIDO_PROD
	FOREIGN KEY(FK_COD_PEDIDO) REFERENCES TB_PEDIDO(COD_PEDIDO),
	FK_COD_PRODUTO INT NOT NULL CONSTRAINT FK_PRODUTO_COD_PRODUTO
	FOREIGN KEY(FK_COD_PRODUTO) REFERENCES TB_PRODUTO(COD_PRODUTO),
	QTDE_ITENS_COMPRADOS SMALLINT NOT NULL
);

CREATE TABLE TB_PEDIDO_FPGTO(	
	COD_PGTO INT IDENTITY(1042,1)
	CONSTRAINT PK_TB_PEDIDO_FPGTO PRIMARY KEY(COD_PGTO),
	NUM_NOTA_FISCAL SMALLINT NOT NULL,
	FK_COD_PEDIDO INT NOT NULL CONSTRAINT FK_PEDIDO_COD_PEDIDO 
	FOREIGN KEY(FK_COD_PEDIDO)REFERENCES TB_PEDIDO(COD_PEDIDO),
	FK_COD_PGTO INT NOT NULL CONSTRAINT FK_FORMA_PGTO_COD_PGTO 
	FOREIGN KEY(FK_COD_PGTO)REFERENCES TB_FORMA_PGTO(ID_PGTO),
);

-- FIM DA CRIAÇÃO DE TABELAS --